language: python

python:
  - "3.8"

name: Deploy
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - python3 setup.py sdist bdist_wheel
  - docs/make html
  - touch _build/html/.nojekyll
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./docs/_build/html
    committer_from_gh: true
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    username: "__token__"
    password:
      secure: "eq37lpDXEb+hT1EbVzpRz/h7GXPr3+/BmMICmK1YLNuhQMfIwGUt6uqWeALC4gi9rNTq/ClJDCnSJLcEVgbVGwNVAhOZrKV7dTzHMBZhhiqVQ8UYOlI/jvAIYc2WGpn3uAbKpXw3+yjSsK4LbR8y5WvBfezufT/67eeqs33zL9sGV8n83cUIH7sufsBug9F9f6qH9buqF/C/WQ1H+g3VrUPKMykTuUjs+u7l9Ck0E+6dOLiZD49t4p04GHyp3Ee/46d1aF53LKDTUW83v1TI/9xeHqGukIMtKnm2Tau8NV/kvL/cMzbiDIFwjDSZbzDX+fZzpPUmUGl0pK6P7sJEPX5wO+2P7ieMQgxM4CB0Jbc8fyvYoinjgjJKY3ed0NTe8jMNy5iwGw3oBAXjiK5P/dUYJE0ds5d/Y7tUHq/kZBmidGcrRe/jcJjUpqBKACKeUJFuVpq36rtzhCvMXgiO8svOO/ruNenUd3TvxnutL4IoZAA16wvuZ0QmlrbV78gOBVitwLl6zxo/3LxiWV3Ylua8/ww9QM++MGuI8fJ5b3WPF0vQpoCXVhrhrNUuKbh88iuSQi+uGIkDNDtZzSJqsfnqHfIAPNdbQeLzEWx0sI4sK+SquunwtIlVuAm7j4Ozj/qHbBmqOQkjrb07D1Rdsvkb8XhyDndFgtfK1nQm270="